# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7bd864cf706ef2b863bb73294f4a72ad757c6dadd9e864aae271defdf39dbda849c2b83bb9a3a3a756dff371d7e9aecd34907b3aeadbf417a1a1cbf37c5825

test:
  secret_key_base: d98b2e40282ffc50cbc4eae193c96ac97bd7cdff6bde207f671d31c4cce79050f8de169131aab7ea5cf9b121a43f54254003c518a9b50bdaf6d68b90fed05dad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
